### ISSUE TITLE
Multiple Initiators

### ISSUE THREAD

**Issue by VjeraTurk** [bidiu/mega-merger#1]
Is it possible to have multiple initiators?
"The algorithm can be initiated spontaneously at any node or at **any subset** of
nodes" (http://www.cs.tau.ac.il/~afek/p66-gallager.pdf)

**Comment by bidiu** [comment]
Hi, I just checked the code. If I'm right, actually once the algorithm starts, every node will spontaneously send a message to its peer, asking if they have joined already. So I think every node is an initiator.

I assume you think it's not the case because you need to click on a node to kick off the algorithm. It's just a way to start the whole thing because there isn't any UI control. And there was no easy way to do that in [the simulation environment](http://jbotsim.io/).

**Comment by VjeraTurk** [comment]
Ok, so in your implementation all the nodes start the execution. Thank you for your answer!

**Comment by bidiu** [comment]
Happy to help!
